runtime: nodejs10  # Serve all static files with urls ending with a file extension

handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
